### ISSUE TITLE
BS 1.25.1 Black screen upon startup

### ISSUE THREAD

**Issue by Capn-evil-i** [ComputerElite/play3rdper#13]
i use replay mod that could be the reason otherwise idk i disabled all mods  and only have third person mod enabled and it still gives me black screen

**Comment by ComputerElite** [comment]
Hold a, b, y, x, both triggers and both grips for-20 seconds while in game

**Comment by Capn-evil-i** [comment]
> Hold a, b, y, x, both triggers and both grips for-20 seconds while in game

thank you so much! this worked! please put this in the description for other people that way they dont get lost like i did lol
