### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Motisimo** [ComputerElite/play3rdper#2]
Hi, I don’t know if I’m allowed to type in here but I’m having an issue that I’ve been noticing with the mod where when I open beat saber with the play3rdper mod all I see is black and the background music plays sometimes and I can feel the vibrations when my controller hovers over the buttons in game and can click the buttons and it makes the click noise. This happens only with this mod and it happens with or without any other mods enabled except core mods.

https://user-images.githubusercontent.com/90792010/133898385-5e4b93d1-8d17-487f-a63e-57653425675a.MP4

**Comment by ComputerElite** [comment]
Hold a, b, y, x both triggers and both grip buttons for ~20sec while the game is running
