### ISSUE TITLE
Too far under the ground

### ISSUE THREAD

**Issue by Tman564ws1** [ComputerElite/play3rdper#5]

**Comment by Tman564ws1** [comment]
Sorry about that. Every time I push the button I go farther and farther underground and now I'm just in a void. Is there any way to reset it? Through the controller.

**Comment by ComputerElite** [comment]
Yep, hold a, b, y, x, both triggers and both grips for ~20 seconds

**Comment by Tman564ws1** [comment]
Yes I started looking for the older versions and I found out that you set up the hard reset for one of them. Sorry, I forgot to tell you.
