### ISSUE TITLE
Add a way to reset config

### ISSUE THREAD

**Issue by elevatorctln** [ComputerElite/play3rdper#7]
When using with the replay mod, if I press Y the offset values get set to -100 each. To fix it I'd have to manually set each one back to zero which is insane considering it goes .1 at a time. Please add a way to reset the config

**Comment by ComputerElite** [comment]
Hold a, b, x, y both grips and both triggers for ~20 seconds

**Comment by elevatorctln** [comment]
Thank you for the very quick reply. I tried that twice, once in the main menu and once in the mod settings and it did nothing. I held them for 30 seconds

**Comment by ComputerElite** [comment]
Make sure that you really pressed all buttons at the same time. It works for about everyone. Perhaps I could ask someone to try it if it still doesn't work for you
