### ISSUE TITLE
Problem at 1.25.1

### ISSUE THREAD

**Issue by phatal** [ComputerElite/play3rdper#8]
When try to launch game  with installed "Third Person mod" for a moment (for a fraction of a second) I see main menu and after only black screen. At the same time game is not stucked or crash because I can hear sound when controller point to the elements of menu (sounds on hover).

**Comment by ComputerElite** [comment]
Hold a, b, x, y, both triggers and both grips for~20 seconds

**Comment by phatal** [comment]
Your solution didn't help (or I just not fully correct understand what I need to do) but i found a solution (may be it will help somebody else):

- Go to (in any file explorer): `ModData/com.beatgames.beatsaber/Configs/` 
- Open `play3rdper.json`
- Change fields `X offset`, `Y offset` and `Z offset` to `0.0`
- Save
...
PROFIT.

**Comment by ComputerElite** [comment]
That's what happens when you hold all those buttons

**Comment by Hk-5** [comment]
Um on the quest version of this mod, in multi player you can load into the lobby where everyone gets to choose their song but as soon as a decision has been made and everyone goes to load in for a split second it shows the waiting for other players and crashes the game. Please fix this.

**Comment by Hk-5** [comment]
And yes i know its this mod because I disabled everything but the core mods and left third person running and only then is when I have this issue

**Comment by ComputerElite** [comment]
I'm aware of that issue and just got the pull request to fix the bug. Thanks for reminding me to ask for that fixed version.
See #9

**Comment by ComputerElite** [comment]
The issue has been fixed in the latest release @Hk-5 

As the other part of the issue has not had any other comments I'm closing this issue. If any other issues arise feel free to open another issue

**Comment by Hk-5** [comment]
Thank you
